sudo: required
services:
  - docker

before_install:
  - docker build -t magiclost/react-test -f ./client/Dockerfile.dev .

# run our testing commands for our images
script:
  - docker run magiclost/react-test npm run test

# build production versions of our images
after_success:
  - docker build -t magiclost/multi-client ./client
  - docker build -t magiclost/multi-nginx ./nginx
  - docker build -t magiclost/multi-server ./ server
  - docker build -t magiclost/multi-worker ./worker
  # Login to Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and set to Docker Hub
  - docker push magiclost/multi-client
  - docker push magiclost/multi-nginx
  - docker push magiclost/multi-server
  - docker push magiclost/multi-worker
